In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [3]:
import numpy as np
 
arr = np.array([1, 2, 3])
print(arr)
 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
 
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [4]:
arr = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)


[1 2 3 4 5]


In [5]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [6]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
std_dev = np.std(arr)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


In [7]:
# Reshaping a 1D array to a 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
